// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaovietServerBlazorApp.Data;

namespace SaovietServerBlazorApp.Migrations
{
    [DbContext(typeof(SaovietContext))]
    [Migration("20210617120853_add-address-id")]
    partial class addaddressid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SaovietServerBlazorApp.Models.AddressModel", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommuneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SaovietServerBlazorApp.Models.OSMaterialWHCheckModel", b =>
                {
                    b.Property<int>("OSCheckingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErrorId")
                        .HasColumnType("int");

                    b.Property<int>("Excess")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRelease")
                        .HasColumnType("bit");

                    b.Property<int>("OutsoleSupplierId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Reject")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleasedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnReject")
                        .HasColumnType("int");

                    b.Property<int>("ReturnRemark")
                        .HasColumnType("int");

                    b.Property<string>("SizeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeNoUpper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkingCard")
                        .HasColumnType("int");

                    b.HasKey("OSCheckingID");

                    b.ToTable("OutsoleMaterialCheckingList");
                });

            modelBuilder.Entity("SaovietServerBlazorApp.Models.OrderModel", b =>
                {
                    b.Property<string>("ProductNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ETD")
                        .HasColumnType("datetime2");

                    b.Property<string>("GTNPONo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<string>("LastCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidsoleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutsoleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatternNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reviser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShoeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfShoes")
                        .HasColumnType("int");

                    b.Property<string>("UCustomerCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductNo");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SaovietServerBlazorApp.Models.OutsoleSupplierModel", b =>
                {
                    b.Property<int>("OutsoleSupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierOperation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutsoleSupplierId");

                    b.ToTable("OutsoleSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
